language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-android-m2repository
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
- yes | sdkmanager "platforms;android-28"
before_script:
- chmod +x gradlew
script:
  # Build parameter 'dev' ensures that the google-services.json
  # file in app/src/dev is used
  - ./gradlew build -Pbuild=dev --stacktrace